# Exercise 1

* Use the dataset

```python
X = [["X","High"],["Y","Low"],["Z","Medium"],["X","Low"]]
```
* Apply One-hot encoding to all variables
* Apply One-hot encoding to the first column and ordinal encoding to the second column following the rank Low, Medium, High

In [6]:
import numpy as np
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder
from sklearn.compose import ColumnTransformer

In [20]:
X = [["X","High"],["Y","Low"],["Z","Medium"],["X","Low"]]
np.array(X)

array([['X', 'High'],
       ['Y', 'Low'],
       ['Z', 'Medium'],
       ['X', 'Low']], dtype='<U6')

In [23]:
encoder = ColumnTransformer([("first Column", OneHotEncoder(), [0]),
                            ("second Column", OrdinalEncoder(categories=[["Low", "Medium", "High"]]), [1])])

In [24]:
encoder.fit_transform(X)

array([[1., 0., 0., 2.],
       [0., 1., 0., 0.],
       [0., 0., 1., 1.],
       [1., 0., 0., 0.]])

# Exercise 2

* Use the dataset

```python
X = [["X","High"],["Y","Low"],["Z","Medium"],["X","Low"]]
```
* Apply One-hot encoding to the first variable and ordinal encoding to the second variable. 
  * The first variable must be encoded considering this set of values: X, Y, Z, W. 
  * The second variable must be encoded considering this set of ranked values: Low, Medium, High, Very high
* Consider the dataset:
```python
Y = [["W","Very high"]]
```
* Transform this dataset according to the fitted encoder

In [25]:
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, OrdinalEncoder

In [26]:
X = [["X","High"],["Y","Low"],["Z","Medium"],["X","Low"]]
np.array(X)

array([['X', 'High'],
       ['Y', 'Low'],
       ['Z', 'Medium'],
       ['X', 'Low']], dtype='<U6')

In [27]:
encoder = ColumnTransformer([("first column", OneHotEncoder(categories=[["X", "Y", "Z", "W"]]), [0]),
                             ("second column", OrdinalEncoder(categories=[["Low", "Medium", "High", "Very high"]]),[1])])

In [28]:
encoder.fit_transform(X)

array([[1., 0., 0., 0., 2.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0.]])

In [29]:
Y = [["W","Very high"]]

In [30]:
encoder.transform(Y)

array([[0., 0., 0., 1., 3.]])