# Numerical Features and Numerical Target

In [1]:
import pandas as pd
from sklearn.feature_selection  import SelectKBest, f_regression, mutual_info_regression

In [2]:
df = pd.read_csv("../../Datasets/sample_dataset.csv").iloc[:, 0:12].dropna()

In [4]:
X = df.iloc[:, 0:10]
y = df.iloc[:, 10]

### Correlation using F Statistics

In [7]:
selector = SelectKBest(f_regression, k=5)
selector

SelectKBest(k=5, score_func=<function f_regression at 0x000002BD11617BA0>)

In [8]:
selector.fit(X, y)

SelectKBest(k=5, score_func=<function f_regression at 0x000002BD11617BA0>)

In [9]:
selector.transform(X)

array([[1.300e+01, 8.750e+01, 5.198e+02, 1.859e-01, 9.353e-02],
       [1.981e+01, 1.300e+02, 1.260e+03, 1.479e-01, 9.498e-02],
       [1.308e+01, 8.563e+01, 5.200e+02, 4.568e-02, 3.110e-02],
       [9.504e+00, 6.034e+01, 2.739e+02, 2.956e-02, 2.076e-02],
       [1.348e+01, 8.840e+01, 5.592e+02, 1.063e-01, 5.439e-02],
       [1.328e+01, 8.732e+01, 5.452e+02, 9.847e-02, 6.158e-02],
       [1.305e+01, 8.261e+01, 5.272e+02, 6.920e-04, 4.167e-03],
       [9.173e+00, 5.920e+01, 2.609e+02, 5.988e-02, 2.180e-02],
       [1.268e+01, 8.269e+01, 4.990e+02, 1.128e-01, 6.873e-02],
       [1.311e+01, 8.721e+01, 5.302e+02, 2.071e-01, 9.601e-02],
       [1.510e+01, 9.958e+01, 6.745e+02, 1.138e-01, 8.534e-02],
       [1.845e+01, 1.202e+02, 1.075e+03, 1.153e-01, 6.847e-02],
       [1.180e+01, 7.899e+01, 4.320e+02, 1.659e-01, 7.415e-02],
       [1.206e+01, 7.684e+01, 4.486e+02, 1.972e-02, 1.963e-02],
       [1.080e+01, 6.877e+01, 3.576e+02, 2.531e-02, 1.698e-02],
       [1.008e+01, 6.376e+01, 3.175e+02,

In [10]:
X.columns[selector.get_support()]

Index(['mean radius', 'mean perimeter', 'mean area', 'mean concavity',
       'mean concave points'],
      dtype='object')

### Correlation using Mutual Information

In [11]:
selector = SelectKBest(mutual_info_regression, k = 5)
selector.fit(X, y)

SelectKBest(k=5,
            score_func=<function mutual_info_regression at 0x000002BD11615BC0>)

In [13]:
selector.transform(X), X.columns[selector.get_support()]

(array([[1.300e+01, 8.750e+01, 5.198e+02, 1.859e-01, 9.353e-02],
        [1.981e+01, 1.300e+02, 1.260e+03, 1.479e-01, 9.498e-02],
        [1.308e+01, 8.563e+01, 5.200e+02, 4.568e-02, 3.110e-02],
        [9.504e+00, 6.034e+01, 2.739e+02, 2.956e-02, 2.076e-02],
        [1.348e+01, 8.840e+01, 5.592e+02, 1.063e-01, 5.439e-02],
        [1.328e+01, 8.732e+01, 5.452e+02, 9.847e-02, 6.158e-02],
        [1.305e+01, 8.261e+01, 5.272e+02, 6.920e-04, 4.167e-03],
        [9.173e+00, 5.920e+01, 2.609e+02, 5.988e-02, 2.180e-02],
        [1.268e+01, 8.269e+01, 4.990e+02, 1.128e-01, 6.873e-02],
        [1.311e+01, 8.721e+01, 5.302e+02, 2.071e-01, 9.601e-02],
        [1.510e+01, 9.958e+01, 6.745e+02, 1.138e-01, 8.534e-02],
        [1.845e+01, 1.202e+02, 1.075e+03, 1.153e-01, 6.847e-02],
        [1.180e+01, 7.899e+01, 4.320e+02, 1.659e-01, 7.415e-02],
        [1.206e+01, 7.684e+01, 4.486e+02, 1.972e-02, 1.963e-02],
        [1.080e+01, 6.877e+01, 3.576e+02, 2.531e-02, 1.698e-02],
        [1.008e+01, 6.376

# Numerical Features with Categorical Target

In [24]:
from sklearn.feature_selection import SelectKBest, f_classif, mutual_info_classif

In [19]:
df = pd.read_csv("../../Datasets/sample_dataset.csv").loc[:, ['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension', 'target']].dropna()

In [23]:
X = df.iloc[:, 0:10]
y = df.iloc[:, 10]


### Feature Selection with ANOVA

In [26]:
selector = SelectKBest(f_classif, k=5)
selector.fit(X, y)

SelectKBest(k=5)

In [28]:
selector.transform(X), X.columns[selector.get_support()]

(array([[1.300e+01, 8.750e+01, 5.198e+02, 1.859e-01, 9.353e-02],
        [1.981e+01, 1.300e+02, 1.260e+03, 1.479e-01, 9.498e-02],
        [1.308e+01, 8.563e+01, 5.200e+02, 4.568e-02, 3.110e-02],
        [9.504e+00, 6.034e+01, 2.739e+02, 2.956e-02, 2.076e-02],
        [1.348e+01, 8.840e+01, 5.592e+02, 1.063e-01, 5.439e-02],
        [1.328e+01, 8.732e+01, 5.452e+02, 9.847e-02, 6.158e-02],
        [1.305e+01, 8.261e+01, 5.272e+02, 6.920e-04, 4.167e-03],
        [9.173e+00, 5.920e+01, 2.609e+02, 5.988e-02, 2.180e-02],
        [1.268e+01, 8.269e+01, 4.990e+02, 1.128e-01, 6.873e-02],
        [1.380e+01, 9.043e+01, 5.841e+02, 7.789e-02, 5.069e-02],
        [1.311e+01, 8.721e+01, 5.302e+02, 2.071e-01, 9.601e-02],
        [1.510e+01, 9.958e+01, 6.745e+02, 1.138e-01, 8.534e-02],
        [1.845e+01, 1.202e+02, 1.075e+03, 1.153e-01, 6.847e-02],
        [1.180e+01, 7.899e+01, 4.320e+02, 1.659e-01, 7.415e-02],
        [1.206e+01, 7.684e+01, 4.486e+02, 1.972e-02, 1.963e-02],
        [1.080e+01, 6.877

### Feature Selection with Mutual Information

In [29]:
selector = SelectKBest(mutual_info_classif, k=5)
selector.fit(X, y)

SelectKBest(k=5,
            score_func=<function mutual_info_classif at 0x000002BD11615D00>)

In [30]:
selector.transform(X), X.columns[selector.get_support()]

(array([[1.300e+01, 8.750e+01, 5.198e+02, 1.859e-01, 9.353e-02],
        [1.981e+01, 1.300e+02, 1.260e+03, 1.479e-01, 9.498e-02],
        [1.308e+01, 8.563e+01, 5.200e+02, 4.568e-02, 3.110e-02],
        [9.504e+00, 6.034e+01, 2.739e+02, 2.956e-02, 2.076e-02],
        [1.348e+01, 8.840e+01, 5.592e+02, 1.063e-01, 5.439e-02],
        [1.328e+01, 8.732e+01, 5.452e+02, 9.847e-02, 6.158e-02],
        [1.305e+01, 8.261e+01, 5.272e+02, 6.920e-04, 4.167e-03],
        [9.173e+00, 5.920e+01, 2.609e+02, 5.988e-02, 2.180e-02],
        [1.268e+01, 8.269e+01, 4.990e+02, 1.128e-01, 6.873e-02],
        [1.380e+01, 9.043e+01, 5.841e+02, 7.789e-02, 5.069e-02],
        [1.311e+01, 8.721e+01, 5.302e+02, 2.071e-01, 9.601e-02],
        [1.510e+01, 9.958e+01, 6.745e+02, 1.138e-01, 8.534e-02],
        [1.845e+01, 1.202e+02, 1.075e+03, 1.153e-01, 6.847e-02],
        [1.180e+01, 7.899e+01, 4.320e+02, 1.659e-01, 7.415e-02],
        [1.206e+01, 7.684e+01, 4.486e+02, 1.972e-02, 1.963e-02],
        [1.080e+01, 6.877

# Categorical Features Numerical Target

In [81]:
from sklearn.feature_selection import SelectKBest, mutual_info_regression
from sklearn.preprocessing import OrdinalEncoder
import numpy as np

In [69]:
df = pd.read_csv("../../Datasets/sample_dataset.csv")

In [75]:
X= df.iloc[:, 0:10]
y = df["radius error"]

In [77]:
X = OrdinalEncoder().fit_transform(X)
X

array([[ nan,   1., 411., ..., 357., 360., 432.],
       [370., 164., 440., ..., 267.,  nan,  82.],
       [355., 284., 433., ...,  nan,  nan, 169.],
       ...,
       [296., 399., 370., ..., 221.,  83.,  75.],
       [373., 408., 453., ..., 360., 357.,  nan],
       [  3.,  nan,   1., ...,   0.,  80., 137.]])

In [78]:
selector = SelectKBest(lambda X,y:mutual_info_regression(X, y, discrete_features=True), k=5)

In [82]:
X = np.nan_to_num(X)
y = np.nan_to_num(y)

In [83]:
selector.fit_transform(X, y)

array([[  0., 411., 453., 360., 432.],
       [370., 440.,   0.,   0.,  82.],
       [355., 433., 393.,   0., 169.],
       ...,
       [296., 370., 260.,  83.,  75.],
       [373., 453., 452., 357.,   0.],
       [  3.,   1.,  30.,  80., 137.]])

In [84]:
selector = SelectKBest(lambda X,y:mutual_info_regression(X, y, discrete_features=[0, 1, 2]), k=5)
selector.fit_transform(X, y)

array([[  0., 411., 321., 401., 357.],
       [370., 440., 366., 238., 267.],
       [355., 433., 344.,   0.,   0.],
       ...,
       [296., 370.,   0.,   0., 221.],
       [373., 453., 357., 410., 360.],
       [  3.,   1.,   3.,   0.,   0.]])

# Categorical Feature with Categorical Target

In [87]:
from sklearn.feature_selection import chi2, mutual_info_classif
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder

In [88]:
df = pd.read_csv("../../Datasets/sample_dataset.csv")
X = df.iloc[:, 0:10]
y = df.iloc[:, -1]

In [89]:
X = OrdinalEncoder().fit_transform(X)
y = LabelEncoder().fit_transform(y)

In [91]:
X = np.nan_to_num(X)
y = np.nan_to_num(y)

### Mutual Information

In [92]:
selector = SelectKBest(lambda X, y: mutual_info_classif(X, y, discrete_features=True), k=5)
selector.fit(X, y)

SelectKBest(k=5, score_func=<function <lambda> at 0x000002BD151E98A0>)

In [102]:
selector.transform(X), [selector.get_support()]

(array([[  0., 411., 453., 401., 432.],
        [370., 440.,   0., 238.,  82.],
        [355., 433., 393.,   0., 169.],
        ...,
        [296., 370., 260.,   0.,  75.],
        [373., 453., 452., 410.,   0.],
        [  3.,   1.,  30.,   0., 137.]]),
 [array([ True, False,  True, False, False,  True,  True, False, False,
          True])])

### Chi Square

In [103]:
selector = SelectKBest(chi2, k=5)
selector.fit(X, y)

SelectKBest(k=5, score_func=<function chi2 at 0x000002BD11617920>)

In [105]:
selector.transform(X)

array([[  0., 411., 321., 401., 357.],
       [370., 440., 366., 238., 267.],
       [355., 433., 344.,   0.,   0.],
       ...,
       [296., 370.,   0.,   0., 221.],
       [373., 453., 357., 410., 360.],
       [  3.,   1.,   3.,   0.,   0.]])

# Feature Selection According to Model

In [106]:
from sklearn.ensemble import RandomForestClassifier

In [111]:
from sklearn.feature_selection import SelectFromModel

In [112]:
df = pd.read_csv("../../Datasets/sample_dataset.csv")
df = df.loc[:, ['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension', 'target']].dropna()

In [113]:
X = df.iloc[:, 0:10]
y = df.iloc[:, -1]

In [115]:
model = RandomForestClassifier(random_state=0)
model

RandomForestClassifier(random_state=0)

In [116]:
selector = SelectFromModel(model)
selector

SelectFromModel(estimator=RandomForestClassifier(random_state=0))

In [118]:
selector.fit_transform(X, y)

array([[0.1859  , 0.09353 ],
       [0.1479  , 0.09498 ],
       [0.04568 , 0.0311  ],
       [0.02956 , 0.02076 ],
       [0.1063  , 0.05439 ],
       [0.09847 , 0.06158 ],
       [0.000692, 0.004167],
       [0.05988 , 0.0218  ],
       [0.1128  , 0.06873 ],
       [0.07789 , 0.05069 ],
       [0.2071  , 0.09601 ],
       [0.1138  , 0.08534 ],
       [0.1153  , 0.06847 ],
       [0.1659  , 0.07415 ],
       [0.01972 , 0.01963 ],
       [0.02531 , 0.01698 ],
       [0.001597, 0.002404],
       [0.0755  , 0.04079 ],
       [0.1682  , 0.06597 ],
       [0.1417  , 0.08811 ],
       [0.02638 , 0.02069 ],
       [0.1266  , 0.08353 ],
       [0.0802  , 0.05843 ],
       [0.02245 , 0.02763 ],
       [0.01288 , 0.01924 ],
       [0.01236 , 0.01369 ],
       [0.2197  , 0.1062  ],
       [0.0683  , 0.03099 ],
       [0.01765 , 0.02733 ],
       [0.007756, 0.008535],
       [0.03738 , 0.02098 ],
       [0.2914  , 0.1242  ],
       [0.02556 , 0.02031 ],
       [0.01271 , 0.01117 ],
       [0.0192

In [120]:
X.columns[selector.get_support()]

Index(['mean concavity', 'mean concave points'], dtype='object')

In [121]:
selector

SelectFromModel(estimator=RandomForestClassifier(random_state=0))

In [122]:
selector.estimator_.feature_importances_

array([0.05864691, 0.05857587, 0.08734768, 0.08573085, 0.03495926,
       0.09806245, 0.27767754, 0.26639098, 0.01451452, 0.01809393])

### Limiting Number of Features

In [123]:
selector = SelectFromModel(model, threshold="median", max_features=3)
selector

SelectFromModel(estimator=RandomForestClassifier(random_state=0),
                max_features=3, threshold='median')

In [125]:
selector.fit_transform(X, y)

array([[0.1932  , 0.1859  , 0.09353 ],
       [0.1027  , 0.1479  , 0.09498 ],
       [0.127   , 0.04568 , 0.0311  ],
       [0.06492 , 0.02956 , 0.02076 ],
       [0.1255  , 0.1063  , 0.05439 ],
       [0.1436  , 0.09847 , 0.06158 ],
       [0.03789 , 0.000692, 0.004167],
       [0.08751 , 0.05988 , 0.0218  ],
       [0.1262  , 0.1128  , 0.06873 ],
       [0.128   , 0.07789 , 0.05069 ],
       [0.1765  , 0.2071  , 0.09601 ],
       [0.1807  , 0.1138  , 0.08534 ],
       [0.09709 , 0.1153  , 0.06847 ],
       [0.17    , 0.1659  , 0.07415 ],
       [0.05241 , 0.01972 , 0.01963 ],
       [0.05736 , 0.02531 , 0.01698 ],
       [0.04695 , 0.001597, 0.002404],
       [0.09588 , 0.0755  , 0.04079 ],
       [0.1146  , 0.1682  , 0.06597 ],
       [0.1298  , 0.1417  , 0.08811 ],
       [0.05991 , 0.02638 , 0.02069 ],
       [0.1041  , 0.1266  , 0.08353 ],
       [0.05884 , 0.0802  , 0.05843 ],
       [0.0434  , 0.02245 , 0.02763 ],
       [0.08393 , 0.01288 , 0.01924 ],
       [0.04721 , 0.01236

### Selecting N most important Features

In [126]:
selector = SelectFromModel(model, threshold=-np.inf, max_features=3)
selector

SelectFromModel(estimator=RandomForestClassifier(random_state=0),
                max_features=3, threshold=-inf)

In [127]:
selector.fit_transform(X, y)

array([[0.1932  , 0.1859  , 0.09353 ],
       [0.1027  , 0.1479  , 0.09498 ],
       [0.127   , 0.04568 , 0.0311  ],
       [0.06492 , 0.02956 , 0.02076 ],
       [0.1255  , 0.1063  , 0.05439 ],
       [0.1436  , 0.09847 , 0.06158 ],
       [0.03789 , 0.000692, 0.004167],
       [0.08751 , 0.05988 , 0.0218  ],
       [0.1262  , 0.1128  , 0.06873 ],
       [0.128   , 0.07789 , 0.05069 ],
       [0.1765  , 0.2071  , 0.09601 ],
       [0.1807  , 0.1138  , 0.08534 ],
       [0.09709 , 0.1153  , 0.06847 ],
       [0.17    , 0.1659  , 0.07415 ],
       [0.05241 , 0.01972 , 0.01963 ],
       [0.05736 , 0.02531 , 0.01698 ],
       [0.04695 , 0.001597, 0.002404],
       [0.09588 , 0.0755  , 0.04079 ],
       [0.1146  , 0.1682  , 0.06597 ],
       [0.1298  , 0.1417  , 0.08811 ],
       [0.05991 , 0.02638 , 0.02069 ],
       [0.1041  , 0.1266  , 0.08353 ],
       [0.05884 , 0.0802  , 0.05843 ],
       [0.0434  , 0.02245 , 0.02763 ],
       [0.08393 , 0.01288 , 0.01924 ],
       [0.04721 , 0.01236

In [128]:
X.columns[selector.get_support()]

Index(['mean compactness', 'mean concavity', 'mean concave points'], dtype='object')