#### Numpy vs list speed comparison

In [2]:
import numpy as np
import time
lst = list(range(100000000))
arr = np.arange(100000000)

start = time.time()
sum(lst)
print("List ",time.time() - start)

start = time.time()
np.sum(arr)
print("Numpy", time.time() - start)

List  1.131951093673706
Numpy 0.03301572799682617


#### Ndarray

In [4]:
arr1 = np.array([1,2,3,4])
arr1

array([1, 2, 3, 4])

In [6]:
arr2 = np.array([[1,2,3,4], [2,3,4,5]])
arr2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

#### Array Operations

In [7]:
arr_a = np.array([1,2,3])
arr_b = np.array([4,5,6])

print("Addition: ", arr_a + arr_b)
print("Subtraction: ", arr_b - arr_a)
print("Broadcasting : ", arr_a + 5)

Addition:  [5 7 9]
Subtraction:  [3 3 3]
Broadcasting :  [6 7 8]


###### Case Study 1
Create a 5X5 Matrix for Integers between 1 to 25

In [10]:
arr = np.arange(1,26)
arr = arr.reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

###### Case Study 2
Create a 3X3 Matrix as  middle of previous matrix.

In [15]:
mid = arr[1:4, 1:4]
mid

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

###### Case 3 
Row Wise Sum

In [16]:
np.sum(arr, axis=1)

array([ 15,  40,  65,  90, 115])

###### Case 4
Column Wise Sum

In [17]:
np.sum(arr, axis=0)

array([55, 60, 65, 70, 75])

# Case Study : Insurance Company
Monthly Claim Analysis 

In [18]:
policy_claims = np.array([
    [12000, 15000, 18000],
    [10000, 13000, 17000],
    [9000, 11000, 16000]])
policy_claims

array([[12000, 15000, 18000],
       [10000, 13000, 17000],
       [ 9000, 11000, 16000]])

In [20]:
# Get the Claim Amount for Person 3 in Month 1
# Get the Claim Amount for Person 1 in Month 3
policy_claims[2, 0], policy_claims[0,2]

(9000, 18000)

In [21]:
# Average Claim amount per month
np.mean(policy_claims, axis =0)

array([10333.33333333, 13000.        , 17000.        ])

In [22]:
# Average Claim amount per Person
np.mean(policy_claims, axis=1)

array([15000.        , 13333.33333333, 12000.        ])

# Case Study : Customer Feedback Analysis
- Import mixed data using numpy
- Analyze customer ratings statistically
- Extract Text for Qualitative Analysis

In [1]:
import numpy as np

data = np.array([
    ["C001", 5 , "Excellent Service and friendly staff"],
    ["C002", 4 , "Good Product selection but long wait time"],
    ["C003", 3 , "Average Experience , Checkout was slow"],
    ["C004", 5 , "Loved the discounts! will shop again"],
    ["C005", 2 , "Poor Customer support, not satisfied"],
    ["C006", 4 , "Good quality but a bit expensive"],
    ["C007", 1 , "Terrible Experience, rudestaff"],
    ["C008", 5 , "Amazing Deals and fast service"],
])

In [3]:
print(data)

[['C001' '5' 'Excellent Service and friendly staff']
 ['C002' '4' 'Good Product selection but long wait time']
 ['C003' '3' 'Average Experience , Checkout was slow']
 ['C004' '5' 'Loved the discounts! will shop again']
 ['C005' '2' 'Poor Customer support, not satisfied']
 ['C006' '4' 'Good quality but a bit expensive']
 ['C007' '1' 'Terrible Experience, rudestaff']
 ['C008' '5' 'Amazing Deals and fast service']]


#### Step 2 : Quantitative Statistical Analysis

In [5]:
ratings = data[:,1].astype(int)
ratings

array([5, 4, 3, 5, 2, 4, 1, 5])

In [6]:
np.max(ratings), np.mean(ratings), np.min(ratings)

(5, 3.625, 1)

In [8]:
unique_ratings , rating_counts = np.unique(ratings, return_counts=True)
unique_ratings , rating_counts

(array([1, 2, 3, 4, 5]), array([1, 1, 1, 2, 3], dtype=int64))

#### Step 3: Qualitative Analysis

In [10]:
feedback_comments = data[:, 2] 
# Display Insights
for rating, count in zip(unique_ratings, rating_counts):
    print(f"Rating {rating} : {count} customers")

Rating 1 : 1 customers
Rating 2 : 1 customers
Rating 3 : 1 customers
Rating 4 : 2 customers
Rating 5 : 3 customers


#### Step 4 : Summary

In [11]:
for feedback in feedback_comments[:5]:
    print(feedback)

Excellent Service and friendly staff
Good Product selection but long wait time
Average Experience , Checkout was slow
Loved the discounts! will shop again
Poor Customer support, not satisfied


# Case Study : Policy Holder Data Transformation in Insurance Industry

- How to Manipulate structured data using numpy
- Perform column swapping in a numpy array
- Gain Insights into real-world insurance data handling.

In [13]:
# Import Libraries
import numpy as np
import pandas as pd

#### Step1 : Prepare the dataset

In [16]:
policy_data = np.array([
    [1001, 12000, 500000, 5000],
    [1002, 15000, 750000, 7000],
    [1003, 18000, 1000000, 10000],
    [1004, 20000, 1200000, 12000],
    [1005, 25000, 1500000, 15000]
])
col = ["Policy Number", "Premium Amount", "Insured Amount", "Claim Amount"]
df_before = pd.DataFrame(policy_data, columns=col)
df_before

Policy Number  Premium Amount  Insured Amount  Claim Amount
0           1001           12000          500000          5000
1           1002           15000          750000          7000
2           1003           18000         1000000         10000
3           1004           20000         1200000         12000
4           1005           25000         1500000         15000

#### Step 2 : Swap Columns (Premium Amount and Claim Number)

In [20]:
policy_data[:,[1,3]] =policy_data[:,[3,1]]
policy_data

array([[   1001,    5000,  500000,   12000],
       [   1002,    7000,  750000,   15000],
       [   1003,   10000, 1000000,   18000],
       [   1004,   12000, 1200000,   20000],
       [   1005,   15000, 1500000,   25000]])

In [22]:
df_after = pd.DataFrame(policy_data, columns=col)
# Premium Amount is now swapped with Claim Amount
df_after

Policy Number  Premium Amount  Insured Amount  Claim Amount
0           1001            5000          500000         12000
1           1002            7000          750000         15000
2           1003           10000         1000000         18000
3           1004           12000         1200000         20000
4           1005           15000         1500000         25000

#### Step 4: Calculate the total Claim Amount Processed

In [23]:
print(np.sum(policy_data[:, 3]))

90000
