In [1]:
import numpy as np

# 1: Create a 1D NumPy array with integers from 1 to 20. Perform the following operations:

In [4]:
arr = np.arange(1,21)

### Calculate the sum, mean, median, and standard deviation of the elements in the array.  


In [12]:
print(f"Sum : {np.sum(arr)}")
print(f"Mean : {np.mean(arr)}")
print(f"Median : {np.median(arr)}")
print(f"Standard Deviation : {np.std(arr)}")

Sum : 210
Mean : 10.5
Median : 10.5
Standard Deviation : 5.766281297335398


### Find the indices of elements greater than 10 in the array.

In [26]:
print("The Indices for Elements Greater than 10 are")
for i in np.where(arr > 10)[0]:
    print(i, end=" ")

The Indices for Elements Greater than 10 are
10 11 12 13 14 15 16 17 18 19 

# 2. Create a 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.

In [14]:
arr2d = np.arange(1,17).reshape(4,4)

### Print the array.  

In [27]:
print(arr2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


 ### Find the transpose of the array. 

In [28]:
arr2dTra = np.transpose(arr2d)
print(arr2dTra)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


### Calculate the row-wise and column-wise sums of the array.

In [34]:
print("Row Wise Sum : ",np.sum(arr2d, axis=1))
print("Column Wise Sum : ", np.sum(arr2d, axis=0))

Row Wise Sum :  [10 26 42 58]
Column Wise Sum :  [28 32 36 40]


# 3. Create two 3 X 3 arrays filled with random integers between 1 and 20.

In [48]:
arr1 = np.random.randint(1, 20, size=9).reshape(3,3)
arr2 = np.random.randint(1, 20, size=9).reshape(3,3)

### Perform element-wise addition, subtraction, and multiplication

In [55]:
print("Array 1 : ")
print(arr1)
print("Array 2 : ")
print(arr2)

Array 1 : 
[[ 6 17 19]
 [ 7 10  8]
 [18 15 15]]
Array 2 : 
[[13 14  9]
 [ 1 16 16]
 [14  8 12]]


In [56]:
print("Element wise sum of the Arrays : ")
print(arr1 + arr2)

Element wise sum of the Arrays : 
[[19 31 28]
 [ 8 26 24]
 [32 23 27]]


In [57]:
print("Element wise Subtraction")
print(arr1 - arr2)

Element wise Subtraction
[[-7  3 10]
 [ 6 -6 -8]
 [ 4  7  3]]


In [58]:
print("Element wise multiplication")
print(arr1 * arr2)

Element wise multiplication
[[ 78 238 171]
 [  7 160 128]
 [252 120 180]]


### Compute the dot product of the two arrays

In [60]:
print(np.dot(arr1, arr2))

[[361 508 554]
 [213 322 319]
 [459 612 582]]


# 4. Reshape a 1D array of size 12 into a 3 X 4 2D array and slice the first two rows and last two columns. 

In [62]:
arr_f = np.arange(1,13).reshape(3,4)
print(arr_f)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [71]:
print("First 2 Rows")
arr_f[:2,:]

First 2 Rows


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [70]:
print("Last 2 Columns")
arr_f[:,-2:]

Last 2 Columns


array([[ 3,  4],
       [ 7,  8],
       [11, 12]])